### ISSUE TITLE
Horizontal bar incorrectly extends to fit last rule name

### ISSUE THREAD

**Issue by MDLC01** [pauladam94/curryst#1]
Consider the following proof tree:
```typ
#proof-tree(
  rule(
    [Conclusion],
    rule(
      name: [Very long rule name],
      [x],
      [y],
    ),
  )
)
```

When this tree is rendered, the second horizontal line is extended to fit the very long rule name:

![image](https://github.com/pauladam94/curryst/assets/57839069/6af7efe3-64e3-40ca-b314-951818b4181e)

Instead, I would expect the tree to be rendered the following way:

![image](https://github.com/pauladam94/curryst/assets/57839069/8aa4586d-a87e-41dd-9cc2-76f5da4500ef)

**Comment by pauladam94** [comment]
This behaviour is very complicated to implement. But yes it should be like that.

Right now, I get recursively the size of anything that is above the rule. When I get the size, it is gard to tell that something is taking some place but in a important way.

In the code it is actually intended to have this kind of behaviour because of the presence of "left-blank" and "right blank". There are passed recursively to the next rule. It should use in a better way.

**Comment by MDLC01** [comment]
Note that this result can still be achieved by wrapping inner rules inside `prooftree` in order to treat them as content instead of as nested rules:

```typ
#prooftree(
  rule(
    [Conclusion],
    prooftree(rule(
      name: [Very long rule name],
      [x],
      [y],
    )),
  )
)
```

<img width="848" height="423" alt="The rule name causes the bar of the main tree to extend." src="https://github.com/user-attachments/assets/fed27415-8c77-4d4e-9247-723601d3b2bb" />

Not saying the API couldn't be improved though, as this is not really an intended design, more of a workaround.
