### ISSUE TITLE
Is it expected that large proof trees exceed the show rule depth limit?

### ISSUE THREAD

**Issue by schuelermine** [pauladam94/curryst#19]
I was setting a big proof like this one:

![Screenshot from 2024-05-17 00-20-31](https://github.com/pauladam94/curryst/assets/48802534/39d4d4a7-5ae0-417e-b653-72ce7508b8bb)

Adding one more layer causes Typst to complain. Is this expected?

**Comment by MDLC01** [comment]
This is not expected. Could you send the code that produces the issue?

**Comment by schuelermine** [comment]
Here’s a minimal reproducible example:

```typ
#import "@preview/curryst:0.3.0": proof-tree, rule

#proof-tree(
  rule(
    $a$,
    rule(
      $b$,
      rule(
        $c$,
        rule(
          $d$,
          rule(
            $e$,
            rule(
              $f$,
              rule(
                $g$,
                rule(
                  $h$,
                  rule(
                    $i$,
                    rule(
                      $j$,
                      rule(
                        $k$,
                        rule(
                          $l$,
                          rule(
                            $m$,
                            rule(
                              $n$,
                              rule(
                                $o$
                              )
                            )
                          )
                        )
                      )
                    )
                  )
                )
              )
            )
          )
        )
      )
    )
  )
)
```

**Comment by MDLC01** [comment]
After taking a deeper look, I think this is a Typst limitation. I would not say it is expected behavior, but you just reached the limit of what Typst is able to do. Sadly, there is not much we can do about this as a package.

Tracking down the exact limitation is hard (the problem is actually not directly related to show rules, see typst/typst#4171). I tried to remove some calls to `measure`, but could not get it to compile the example you provided.

**Comment by schuelermine** [comment]
Thank you for the confirmation.
